// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: addPhg.sql

package database

import (
	"context"
)

const addPhotographer = `-- name: AddPhotographer :exec
INSERT INTO photographers (phgname,phgusername,phgmobile,phgpassword)
VALUES ($1,$2,$3,$4)
RETURNING id, phgname, phgusername, phgmobile, phgpassword
`

type AddPhotographerParams struct {
	Phgname     string
	Phgusername string
	Phgmobile   string
	Phgpassword string
}

func (q *Queries) AddPhotographer(ctx context.Context, arg AddPhotographerParams) error {
	_, err := q.db.ExecContext(ctx, addPhotographer,
		arg.Phgname,
		arg.Phgusername,
		arg.Phgmobile,
		arg.Phgpassword,
	)
	return err
}
