// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: getPhgs.sql

package database

import (
	"context"
)

const getAllPHotographers = `-- name: GetAllPHotographers :many
SELECT id, phgname, phgusername, phgmobile, phgpassword FROM Photographers
`

func (q *Queries) GetAllPHotographers(ctx context.Context) ([]Photographer, error) {
	rows, err := q.db.QueryContext(ctx, getAllPHotographers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Photographer
	for rows.Next() {
		var i Photographer
		if err := rows.Scan(
			&i.ID,
			&i.Phgname,
			&i.Phgusername,
			&i.Phgmobile,
			&i.Phgpassword,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
