// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: getUserForAuth.sql

package database

import (
	"context"
)

const getUserAuth = `-- name: GetUserAuth :one
SELECT id, name, username, email, mobile, password FROM users WHERE username = $1 AND password = $2
`

type GetUserAuthParams struct {
	Username string
	Password string
}

func (q *Queries) GetUserAuth(ctx context.Context, arg GetUserAuthParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserAuth, arg.Username, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Mobile,
		&i.Password,
	)
	return i, err
}
