// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: insertUsers.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (name,username,email,mobile,password)
VALUES($1,$2,$3,$4,$5)
RETURNING id, name, username, email, mobile, password
`

type CreateUserParams struct {
	Name     string
	Username string
	Email    string
	Mobile   string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.Name,
		arg.Username,
		arg.Email,
		arg.Mobile,
		arg.Password,
	)
	return err
}
