// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

type Photographer struct {
	ID          int32
	Phgname     string
	Phgusername string
	Phgmobile   string
	Phgpassword string
}

type User struct {
	ID       int32
	Name     string
	Username string
	Email    string
	Mobile   string
	Password string
}
