// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: updateUsers.sql

package database

import (
	"context"
)

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET 
name=$1,
username=$2,
email=$3,
mobile=$4 
WHERE id = $5
`

type UpdateUserParams struct {
	Name     string
	Username string
	Email    string
	Mobile   string
	ID       int32
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Name,
		arg.Username,
		arg.Email,
		arg.Mobile,
		arg.ID,
	)
	return err
}
